<?php
 $param = isset($this->params)?$this->params:array();
?>
<!DOCTYPE html>
<html lang="en">
<head><title>Register</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/templates/images/green_dollar.ico" type="image/x-icon">
	<!--Loading bootstrap css-->
	<link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
	<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
	<link type="text/css" rel="stylesheet" href="vendors/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css">
	<link type="text/css" rel="stylesheet" href="/templates/font-awesome/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/bootstrap.css">
	<!--Loading style vendors-->
	<link type="text/css" rel="stylesheet" href="/templates/vendors/animate.css/animate.css">
	<link type="text/css" rel="stylesheet" href="/templates/vendors/iCheck/skins/all.css">
	<!--Loading style-->
	<link type="text/css" rel="stylesheet" href="/templates/css/themes/style1/green-blue.css" id="theme-change" class="style-change color-change">
	<link type="text/css" rel="stylesheet" href="/templates/css/style-responsive.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/common.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/form/login_common.css">
	<link rel="shortcut icon" href="images/favicon.ico">
</head>
<body id="signin-page">

<div class="page-form">

	<form action="/frontend/register" method="post" class="form">
		<div class="header-content"><h1>REGISTER</h1></div>
		<div class="body-content">
			<?php if(isset($this->successMessage)){?>
				<div class="form-group isa_success">
					<i class="fa fa-times-circle"></i>
					<?php echo $this->successMessage; ?>
				</div>
			<?php }?>
			<?php if(isset($this->errorMessage)){?>
				<div class="form-group isa_error">
					<i class="fa fa-times-circle"></i>
					<?php echo $this->errorMessage; ?>
				</div>
			<?php }?>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-user"></i><input type="text" required placeholder="Username" maxlength="20" name="username" value="<?php echo !empty($param)?$param['username']:'';?>" class="form-control"></div>
			</div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-male"></i><input type="text" required placeholder="Full Name" name="fullname" value="<?php echo !empty($param)?$param['fullname']:'';?>" class="form-control"></div>
			</div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-male"></i><input type="password" required placeholder="Password" name="pass" class="form-control"></div></div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-male"></i><input type="password" required placeholder="Sercurity" name="pin" class="form-control"></div>
			</div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-envelope"></i><input type="email" required placeholder="Email" name="email" value="<?php echo !empty($param)?$param['email']:'';?>"  class="form-control"></div>
			</div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-phone"></i><input type="text" required placeholder="Phone" name="phone" value="<?php echo !empty($param)?$param['phone']:'';?>" class="form-control"></div>
			</div>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-bitcoin"></i><input type="text" required placeholder="Bitcoin Address" value="<?php echo !empty($param)?$param['bitaddress']:'';?>" name="bitcoin" class="form-control"></div>
			</div>


			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-trophy"></i>
					<input type="text" placeholder="Sponsor"
						   value="<?php echo isset($this->referer)?$this->referer:''; ?>"
						   name="referer" class="form-control"
						<?php if(isset($this->referer)){?> disabled="disabled" <?php }?>
				</div>
			</div>

			<div class="form-group pull-left">
				<div class="checkbox-list"></div>
			</div>
			<div class="form-group pull-right">
				<button type="submit" class="btn btn-info" style="margin-top: 10px;">Register
					&nbsp;<i class="fa fa-chevron-circle-right"></i></button>
			</div>
			<div class="clearfix"></div>

			<div class="forget-password"><h4>Lost your Password?</h4>

				<p><a href='/customer/resetpassword' class='btn-forgot-pwd'>Reset your password.</a></p></div>
			<hr>
			<p><a id="btn-register" href="/customer/login">Login</a></p></div>
	</form>
</div>
<script src="/templates/js/jquery-1.11.0.min.js"></script>
<script src="/templates/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/templates/js/jquery-ui.js"></script>
<!--loading bootstrap js-->
<script src="/templates/js/bootstrap.min.js"></script>
<script src="/templates/bootstrap-hover-dropdown.js"></script>
<script src="/templates/js/html5shiv.js"></script>
<script src="/templates/js/respond.min.js"></script>
<script src="/templates/vendors/iCheck/icheck.min.js"></script>
<script src="/templates/vendors/iCheck/custom.min.js"></script>

</body>
</html>
 