
<!DOCTYPE html>
<html lang="en">
<head><title>Lost password</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/templates/images/green_dollar.ico" type="image/x-icon">
	<!--Loading bootstrap css-->
	<link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
	<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
	<link type="text/css" rel="stylesheet" href="vendors/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css">
	<link type="text/css" rel="stylesheet" href="/templates/font-awesome/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/bootstrap.css">
	<!--Loading style vendors-->
	<link type="text/css" rel="stylesheet" href="/templates/vendors/animate.css/animate.css">
	<link type="text/css" rel="stylesheet" href="/templates/vendors/iCheck/skins/all.css">
	<!--Loading style-->
	<link type="text/css" rel="stylesheet" href="/templates/css/themes/style1/green-blue.css" id="theme-change" class="style-change color-change">
	<link type="text/css" rel="stylesheet" href="/templates/css/style-responsive.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/common.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/form/login_common.css">
	<link rel="shortcut icon" href="images/favicon.ico">
</head>
<body id="signin-page">
<div class="page-form">
	<form action="/frontend/register/resetpassword" method="post" class="form">
		<div class="header-content"><h1>Lost Password</h1></div>
		<div class="body-content">
			<?php if(isset($this->successMessage)){?>
				<div class="form-group isa_success">
					<!--<i class="fa fa-times-circle"></i>-->
					<?php echo $this->successMessage; ?>
				</div>
			<?php }?>
			<?php if(isset($this->errorMessage)){?>
				<div class="form-group isa_error">
					<!--<i class="fa fa-times-circle"></i>-->
					<?php echo $this->errorMessage; ?>
				</div>
			<?php }?>
			<div class="form-group">
				<div class="input-icon right"><i class="fa fa-user"></i><input type="text" placeholder="Username" name="username" class="form-control"></div>
			</div>
			<div class="form-group pull-left">
				<div class="checkbox-list"></div>
			</div>
			<div class="form-group pull-right">
				<button type="submit" class="btn btn-info">Lost Password
					&nbsp;<i class="fa fa-chevron-circle-right"></i></button>
			</div>
			<div class="clearfix"></div>
			<div class="forget-password"><h4>Login Member</h4>

				<p>Click <a href='/customer/login' class='btn-forgot-pwd'>here</a> to login.</p></div>
			<hr>
			<p>Don't have an account? <a id="btn-register" href="/customer/register">Register Now</a></p></div>
	</form>
</div>
<script src="/templates/js/jquery-1.11.0.min.js"></script>
<script src="/templates/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/templates/js/jquery-ui.js"></script>
<!--loading bootstrap js-->
<script src="/templates/js/bootstrap.min.js"></script>
<script src="/templates/bootstrap-hover-dropdown.js"></script>
<script src="/templates/js/html5shiv.js"></script>
<script src="/templates/js/respond.min.js"></script>
<script src="/templates/vendors/iCheck/icheck.min.js"></script>
<script src="/templates/vendors/iCheck/custom.min.js"></script>

</body>
</html>
 