<div id="main-other">
    <div id="sub-other">
        <div class="other-head">
            <h1>Frequently <span>Asked </span>Question</h1>
        </div>
    </div>
</div>
<div id="main-white">
    <div id="sub-white">
        <div class="otherbox">

            <div class="dc_toggle_container" style="width:100%;">


                <div class="information-head">
                    <h4>General questions</h4>
                </div>
                <!--<div class="rb">
                    <img src="images/rb.png">
                </div>-->


                <br>

                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Where is the company registered?</a></div>
                    <div class="dc_toggle_box" style="display: none;">  The Bio Palm Oil Plantations Ltd company is registered and located in UK with a registration number of 10427145 which can be verified in the United Kingdom Companies House.
                        Our oil palm plantations are strategically located in the various regions of Malaysia and West Africa where the climatic conditions are suitable for planting oil palms. In Malaysia, our plantations are located in the states of Sabah and Sarawak while in West Africa, they are located in Ghana and Nigeria. In addition, the Group also owns oil palm plantations in Colombia and through joint ventures, owns plantations in Brazil and South America.</div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> How safe is the company's website? </a></div>
                    <div class="dc_toggle_box"> GeoTrust Extended Validation Certificates (Green-bar SSL) warranted identity assurance of Palmills.com and security of your transactions up to $1,500,000 with unlimited re-issuance. SiteLock protected the most powerful dedicated servers of Palmills.com in the USA and Europe data centers with hourly malware and vulnerability scans. Our worldwide web servers are protected by Genius Guard, one of the world's largest and most trusted DDoS protection and mitigation provider. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Who can participate in your program and do you accept investors from all countries? </a></div>
                    <div class="dc_toggle_box"> Any individual or corporation from any country may open an account with us and we are happy to accept investors from any place in the world. The only condition is accepting our terms of service. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> How does the referral program work and how much can I earn? </a></div>
                    <div class="dc_toggle_box"> We offer a flexible affiliate program to our customers. It is a great way to make extra money. By inviting more people to our investment programs, or promoting our website using our banners or text ads you earn more of your referral deposit volume. You will instantly receive a commission from any referral that deposits to their account. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What amount of referral reward? </a></div>
                    <div class="dc_toggle_box"> You have an opportunity to earn up to 15% of the deposit, made by your referrals. </div>
                </div>




                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What is a Regional Representatives? </a></div>
                    <div class="dc_toggle_box"> Members from all over the world are offering their assistance in a variety of languages and cultures are ready to be your sponsor to best help you sign up and understand our program. In more detail about it, please read in the "Regional Representatives" section. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Where I can find banners for advertising of the company's program in the Internet? </a></div>
                    <div class="dc_toggle_box"> Log in to your account, then pass into the "Referral Link" section. </div>
                </div>





                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> I want to change my payment data. How to make it? </a></div>
                    <div class="dc_toggle_box"> Please contact us and we will update your account within 12 hours. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> I forgot password. What should I do? </a></div>
                    <div class="dc_toggle_box"> Click on forgot password link, enter your username or e-mail and follow instruction. You'll receive your account reset information by email. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What work schedule of the company's support service? </a></div>
                    <div class="dc_toggle_box"> Business day, from 09:00 - 17:00 UTC. </div>
                </div>





                <br><br>

                <div class="information-head">
                    <h4>Financial questions</h4>
                </div>
               <!-- <div class="rb">
                    <img src="images/rb.png">
                </div>-->


                <br>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What is the minimum and maximum amount that can be withdrawn? </a></div>
                    <div class="dc_toggle_box"> The minimum withdrawal amount is only $0.30 and the maximum amount is not limited. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> When can I withdraw funds from available balance? </a></div>
                    <div class="dc_toggle_box"> You can withdraw funds from your available balance anytime you want and without any fee. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> When will I receive my withdrawal? </a></div>
                    <div class="dc_toggle_box"> All withdrawals are processed instantly. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What is the minimum and maximum amount of deposit? </a></div>
                    <div class="dc_toggle_box"> The minimum investment amount is only $10 and the maximum amount is $50,000. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> How long will it take to add deposit amount into my account? </a></div>
                    <div class="dc_toggle_box"> Your account will be updated immediately as you deposit. BitCoin deposits will be accepted by script automatically, when the total number of confirmations is 1. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Can I make additional investments at any time? </a></div>
                    <div class="dc_toggle_box"> Yes, there is no limitation. You can make as many deposits as you want. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Are additional deposits into the same account treated separately or they are simply added to the current principal? </a></div>
                    <div class="dc_toggle_box"> Additional deposits into an account will be treated separately and its daily earnings calculated and paid depending on its investment date. It is not possible to merge one of your investment with another one. </div>
                </div>



                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> What electronic payment systems are available in the company's program? </a></div>
                    <div class="dc_toggle_box"> We accept all major payment systems of the market, including PerfectMoney, Payeer and BitCoin. We aim to add Payza and AdvCash in the near future. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Do you pay interests on weekends? </a></div>
                    <div class="dc_toggle_box"> No, business days only. From Monday to Friday. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Do you offer compounding? </a></div>
                    <div class="dc_toggle_box"> No, we do not offer compounding at this time. However, you can re-invest your interest and referral commissions if you wish to do so. All investments will be treated separately. It is not possible to merge your investment with another one. </div>
                </div>


                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> I made a deposit and there is no active fund in transactions history. What do I need to do now? </a></div>
                    <div class="dc_toggle_box"> Please send us your deposit details and we will update your account within 12 hours. </div>
                </div>




                <div class="dc_toggle style2 dc_hide">
                    <div class="ho"><a href="" class="dc_toggle_link"> Can I withdraw funds using a different digital currency? </a></div>
                    <div class="dc_toggle_box"> No, you can request a withdrawal to a payment processor that you have previously deposited from. </div>
                </div>






            </div>


        </div>
    </div>
</div>
