<div class="page-content">
    <div style="background: transparent; border: 0; box-shadow: none !important" class="tab-content pan mtl mbn responsive">
        <div id="tab-form-actions" class="tab-pane fade active in">
            <div class="row">

                <div class="col-lg-12">
                    <div class="panel panel-blue">
                        <div class="panel-heading"> Profit Details </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        <th width="32" style="text-align: center">#</th>
                                        <th style="text-align: center">Date</th>
<!--                                        <th>BTC Wallet</th>-->
                                        <th style="text-align: center">Amount</th>
                                        <th style="text-align: center">Level</th>
                                        <th style="text-align: center">Status</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                                    <?php foreach($this->data as $row){ $i++;
                                    ?>
                                    <tr>
                                        <td style="text-align: center"><?php echo $i;?></td>
                                        <td style="text-align: center"><?php echo $row['senddate'];?></td>
                                        <td style="text-align: center"><?php echo $row['amount'];?></td>
                                        <td style="text-align: center"><?php echo $row['level'];?></td>
                                        <td style="text-align: center"><span class="label label-sm <?php echo $row['color'];?>"><?php echo $row['issuccess'];?></span></td>

                                    </tr>
                                        <?php } ?>
                                    <?php } ?>
                                    </tbody>
                                </table>
                                <br><br>
                            </div></div></div>
                </div>
                <!--END CONTENT--><!--BEGIN FOOTER-->
                <div id="footer">
                    <div class="copyright">2016 © btc-powerup.com - POWER UP YOUR BTC</div>
                </div>
                <!--END FOOTER--></div>
            <!--END PAGE WRAPPER--></div>
    </div>
</div>