<?php
$amountInit =   0.15;
$amount  = isset($this->investData['amount'])?$this->investData['amount']:$amountInit;
$blockchain="https://wallet.btc.com/?gclid=Cj0KEQiAy53DBRCo4en29Zvcla0BEiQAVIDccwlfeEAUAvoUsm-YJDfhcSxYlTRmdvQ9TsQaUyfrdhUaAk0f8P8HAQ#/setup/login";
?>
<link rel="stylesheet" type="text/css" href="/templates/css/form/frontend/invest.css"/>
<!--<link type="text/css" rel="stylesheet" href="/templates/css/form/invest.css">-->
<div class="page-content">
    <div style="background: transparent; border: 0; box-shadow: none !important" class="tab-content pan mtl mbn responsive">
        <div id="tab-form-actions" class="tab-pane fade active in">
            <div style="width: 100%">
                <div class="col-lg-12">
                    <div class="panel panel-blue">
                        <div class="panel-body pan">
                            <div class="">
                                <div style="padding-bottom:24px;" class="bgcab">
                                    <div style="font-size:16px;">
                                        <div class="cabh" style="clear: both;">New deposit section</div>
                                        <form method="post" name="spendform">
                                            <input type="hidden" name="a" value="deposit">
                                            <b>Select a plan:</b><br>

                                            <table cellspacing="1" cellpadding="2" border="0" width="100%"><tbody><tr>
                                                    <td colspan="3">
                                                        <input type="radio" name="h_id" value="1" checked="" onclick="updateCompound()">
                                                        <!--	<input type=radio name=h_id value='1'  checked  > -->

                                                        <b>PLAN A 10% HOURLY 24 HOURS 240%</b></td>
                                                </tr><tr>
                                                    <td class="inheader">Plan</td>
                                                    <td class="inheader" width="200">Spent Amount (BTC)</td>
                                                    <td class="inheader" width="100" nowrap=""><nobr>Hourly Profit (%)</nobr></td>
                                                </tr>
                                                <tr>
                                                    <td class="item">PLAN A 10% HOURLY 24 HOURS 240%</td>
                                                    <td class="item" align="right">$20.00 - $10000.00</td>
                                                    <td class="item" align="right">10.00</td>
                                                </tr>
                                                </tbody></table><br><br>
                                            <script>
                                                cps[1] = [];
                                            </script>
                                            <table cellspacing="1" cellpadding="2" border="0" width="100%"><tbody><tr>
                                                    <td colspan="3">
                                                        <input type="radio" name="h_id" value="4" onclick="updateCompound()">
                                                        <!--	<input type=radio name=h_id value='4'  > -->

                                                        <b>PLAN B 15% HOURLY 48 HOURS 720%</b></td>
                                                </tr><tr>
                                                    <td class="inheader">Plan</td>
                                                    <td class="inheader" width="200">Spent Amount (BTC)</td>
                                                    <td class="inheader" width="100" nowrap=""><nobr>Hourly Profit (%)</nobr></td>
                                                </tr>
                                                <tr>
                                                    <td class="item">PLAN B 15% HOURLY 48 HOURS 720%</td>
                                                    <td class="item" align="right">$20.00 - $10000.00</td>
                                                    <td class="item" align="right">15.00</td>
                                                </tr>

                                                </tbody></table><br><br>
                                            <script>
                                                cps[4] = [];
                                            </script>
                                            <table cellspacing="1" cellpadding="2" border="0" width="100%"><tbody><tr>
                                                    <td colspan="3">
                                                        <input type="radio" name="h_id" value="5" onclick="updateCompound()">
                                                        <!--	<input type=radio name=h_id value='5'  > -->

                                                        <b>PLAN C 20% HOURLY 72 HOURS 1440</b></td>
                                                </tr><tr>
                                                    <td class="inheader">Plan</td>
                                                    <td class="inheader" width="200">Spent Amount (BTC)</td>
                                                    <td class="inheader" width="100" nowrap=""><nobr>Hourly Profit (%)</nobr></td>
                                                </tr>
                                                <tr>
                                                    <td class="item">PLAN C 20% HOURLY 72 HOURS 1440</td>
                                                    <td class="item" align="right">$20.00 - $10000.00</td>
                                                    <td class="item" align="right">20.00</td>
                                                </tr>

                                                </tbody></table><br><br>
                                            <script>
                                                cps[5] = [];
                                            </script>


                                            <table cellspacing="0" cellpadding="2" border="0">
                                                <tbody><tr>
                                                    <td>Your account balance (BTC):</td>
                                                    <td align="right">0.00</td>
                                                </tr>
                                                <tr><td>&nbsp;</td>
                                                    <td align="right">
                                                        <small>
                                                        </small>
                                                    </td>
                                                </tr>
                                                <tr class="coin_no" style="border-top: 1px solid green;">
                                                    <td valign="top" style="padding-top: 5px;">
                                                        <div class="intro">
                                                            1.	Go to <a target="_blank" href="https://localbitcoins.com/?ch=4rwv">localbitcoins.com</a> and get Bitcoins (BTC) if you don't have it.<br>
                                                            2.	<a target="_blank" class="tooltip-right2" title="" href="https://bitcoin.org/#download">Send</a> <?php echo $amount?> Bitcoins (in ONE payment) to the address below.<br>
                                                            &nbsp; &nbsp; If you send <b>any other bitcoin amount</b>, payment system will <b>ignore it</b> !<br>
                                                        </div>
                                                        <div class="intro_send">Send EXACTLY <span class="font12"><?php echo $amount?></span> BTC (<a class="tooltip-fee" href="#" title="" style="font-weight: normal;">plus fees</a>) to:</div>
                                                        <div style="text-align: left">
                                                            <table cellpadding="0" cellspacing="0"><tbody><tr>
                                                                    <td>
                                                                        <div class="addr tooltip-top" title="" style="margin-right: 12px;">
                                                                            <a id="adminaddress" value="<?php echo $this->adminWallet;?>" href="bitcoin:<?php echo $this->adminWallet;?>?amount=<?php echo $amount?>&amp;label=Payment"><?php echo $this->adminWallet;?></a>
                                                                        </div>
                                                                    </td>
                                                                    <td style="min-width:80px">
                                                                        <button  class="btn-wallet tooltip-top4 btn" onclick="window.open('<?php echo $blockchain;?>','_blank', 'location=yes,height=570,width=520' );" title="">Open Wallet</button></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </td>
                                                    <td style="text-align: center; padding-top: 5px;">
                                                        <div class="">
                                                            <img id="upload-image-img" src="/templates/images/no-image.png" style="cursor: pointer; width: 306px;height: 170px ;" />
                                                            <input type="file" id="upload-image" style="display: none; margin-top: 10px;" />
                                                            <button id="submittran" class="btn-wait tooltip-top3 btn2" style="margin-top: 5px; " title=""> &nbsp; <span class="btn-spinner"></span><span id="btn-text">Waiting Verify Image From You &nbsp; </span> </button>
                                                        </div>
                                                    </td>
                                                </tr>
                                                </tbody></table>
                                        </form>

                                        <script language="javascript">
                                            for (i = 0; i<document.spendform.type.length; i++) {
                                                if ((document.spendform.type[i].value.match(/^process_/))) {
                                                    document.spendform.type[i].checked = true;
                                                    break;
                                                }
                                            }
                                            updateCompound();
                                        </script>

                                    </div>

                                </div>

                            </div>


                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    //new Clipboard('.btn-copy');
    var _packageMode = "<?php echo $this->investPackage;?>";
    $(document).ready(function() {
        try {
            $(document).on('click','#upload-image-img',function(){
                $('#upload-image').trigger('click');
            });
            $(document).on('change','#upload-image',function(){
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#upload-image-img')
                        .attr('src', e.target.result)
                };
                reader.readAsDataURL($(this).context.files[0]);
                $('#btn-text').html('Click to submit');
                $('.btn-spinner').remove();
                $('#submittran').prop('disabled',false);
            });
            $(document).on('click','#submittran',function(){
                //var reader = new FileReader();
                //reader.readAsDataURL($('#upload-image').context.files[0]);
                uploadFile('#upload-image',function(){
                    $('#submittran').prop('disabled',true);
                    jAlert('Upload successfull','Success',function(r){
                            if(r){
                                location.href='/frontend/member/investstatus';
                            }
                        });
                });
            });

        } catch (e) {
            alert('ready' + e.message);
        }
    });
    /**
     * upload file
     *
     * @author  :   viettd - 2015/11/18 - create
     * @param
     * @param
     * @return
     */
    function uploadFile(input,callback) {
            var data = new FormData();
            data.append('fileUpload', $(input).get(0).files[0]);
            data.append('_packageMode',  _packageMode);
            $.ajax({
                url : '/frontend/upload/upload',
                type : 'POST',
                loading: true,
                data : data,
                enctype:"multipart/form-data",
                processData : false,
                contentType : false,
                success: function(res){
                    switch (res['status']) {
                        case "1":
                            if(callback){
                                callback();
                            }
                            break;
                        case 201:

                            break;
                        case 202:

                            break;
                        default:

                            break;
                    }
                },
                error: function(){

                }
            });
        };

</script>