<?php
$uri = $this->serverUrl();
?>
<link type="text/css" rel="stylesheet" href="/templates/css/form/backend/admin_waiting.css">
<link type="text/css" rel="stylesheet" href="/templates/css/backend_common.css">
<?php $noimage=$this->noimage; ?>
<div class="page-content-admin">
    <div class="message"></div>
    <div class="w-data-table">
        <!--<div class="w-header-table-fix-1">
            <table class="tbl-header-1 table-bordered main-color">
                <thead>
                <tr>
                    <th width="50px">#</th>
                    <th width="150px">Date</th>
                    <th width="70px" rowspan="2">Duration (days)</th>
                    <th width="100px" rowspan="2">Amount(BTC)</th>
                    <th width="130px" rowspan="2">Total Profit (BTC)</th>
                    <th width="100px" rowspan="2">Status</th>
                    <th rowspan="2">Details Image</th>
                    <th width="150px" rowspan="2">Confirm</th>
                    <th width="50px" rowspan="2">Delete</th>
                </tr>
                <tr>
                    <th colspan="2" class="boder-top-white">User Name</th>
                </tr>
                </thead>
            </table>
        </div>-->
        <div class="w-body-table-fix-1 tbl-data-search" >
            <table id="tbl-seach-1" class="tbl-body-1 table-bordered">
                <thead>
                <tr>
                    <th width="50px" >ID</th>
                    <th width="150px">User Name</th>
                    <th width="">Email</th>
                    <th width="230px">Wallet Address</th>
                    <th width="100px">Mobile</th>
                    <th width="130px">IP</th>
                    <th width="50px">Is<br>Active</th>
                    <th width="50px">Delete</th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                    <?php foreach($this->data as $row){ $i++;
                        ?>
                        <tr class="tr-record" record-id="<?php echo $row['ID'];?>">
                            <td width="50px"><?php echo $row['ID'];?></td>
                            <td width="150px"><?php echo $row['UserName'];?></td>
                            <td width=""><?php echo $row['Email'];?></td>
                            <td width="230px"><?php echo $row['WalletAddress'];?></td>
                            <td width="100px"><?php echo $row['Mobile'];?></td>
                            <td width="130px"><?php echo $row['client_ip'];?></td>
                            <td width="50px" class="text-center"><input type="checkbox" class="active-flg" <?php if(1*$row['isActive']==1){ ?> checked="checked"<?php } ?>></td>
                            <td width="50px" class="text-center"><span class="delete-btn label label-sm label-info" style="cursor: pointer; width: 40px;">X</span></td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>


</div>
<script type="text/javascript" src="/templates/js/form/backend/admin_customer.js"></script>