<?php	echo $this->doctype() ?>
<?php
        $url =  $_SERVER['REQUEST_URI'];
		$uri = explode("/", $url);
		$auth = Zend_Auth::getInstance();
		if($auth->hasIdentity())
		{
			$user			=	$auth->getIdentity();
		}
?>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title><?php echo $this->title;?></title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="/templates/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="/templates/assets/css/metro.css" rel="stylesheet" />
   <link href="/templates/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="/templates/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="/templates/assets/css/style.css" rel="stylesheet" />
   <link href="/templates/assets/css/style_responsive.css" rel="stylesheet" />
   <link href="/templates/assets/css/style_default.css" rel="stylesheet" id="style_color" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/gritter/css/jquery.gritter.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/uniform/css/uniform.default.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/chosen-bootstrap/chosen/chosen.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/bootstrap-datepicker/css/datepicker.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/bootstrap-timepicker/compiled/timepicker.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/bootstrap-colorpicker/css/colorpicker.css" />
   <link rel="stylesheet" href="/templates/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css" />
   <link rel="stylesheet" href="/templates/assets/data-tables/DT_bootstrap.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/bootstrap-daterangepicker/daterangepicker.css" />
   <link rel="stylesheet" type="text/css" href="/templates/assets/uniform/css/uniform.default.css" />
   <link rel="stylesheet" type="text/css" href="/templates/css/bootbox.css" />
   <link rel="stylesheet" type="text/css" href="/templates/css/common.css" />
   <link type="text/css" rel="stylesheet" href="/templates/css/jquery.alerts.css">
   <link rel="shortcut icon" href="/templates/css/images/favicon.ico" />

      <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="/templates/assets/js/jquery-1.8.3.min.js"></script>
   <script type="text/javascript" src = "/templates/js/jquery-1.11.0.min.js"></script>
   <script type="text/javascript" src = "/templates/js/jquery-migrate-1.2.1.js"></script>
   <script src="/templates/js/jquery.alerts.js"></script>
      <script type="text/javascript">
		var jQuery_1_11_0 = $.noConflict(true);
	</script>
   <script src="/templates/assets/breakpoints/breakpoints.js"></script>
   <script src="/templates/assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="/templates/assets/js/jquery.blockui.js"></script>
   <script src="/templates/assets/js/jquery.cookie.js"></script>
   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="/templates/assets/js/excanvas.js"></script>
   <script src="/templates/assets/js/respond.js"></script>
   <![endif]-->
   <script type="text/javascript" src="/templates/assets/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
   <!-- <script type="text/javascript" src="/templates/assets/uniform/jquery.uniform.min.js"></script> -->
   <script type="text/javascript" src="/templates/assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-daterangepicker/date.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-daterangepicker/daterangepicker.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
   <script type="text/javascript" src="/templates/assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
   <script type="text/javascript" src ="/templates/js/bootbox.min.js"></script>
   <script type="text/javascript" src ="/templates/js/common.js"></script>
   <script type="text/javascript" src =" /templates/js/message.js"></script>
   <script src="/templates/assets/js/app.js"></script>
   <script>
      jQuery(document).ready(function() {
         // initiate layout and plugins
         App.init();
      });
   </script>
   <style>
      .page-content{
         min-height: 728px !important;
      }

   </style>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
   <div class="header navbar navbar-inverse navbar-fixed-top">
      <!-- BEGIN TOP NAVIGATION BAR -->
      <div class="navbar-inner">
         <div class="container-fluid">
            <!-- BEGIN LOGO -->
            <a class="brand" href="/backend/home/index">Admin</a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
            <img src="/templates/assets/img/menu-toggler.png" alt="" />
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav pull-right">
               <!-- BEGIN NOTIFICATION DROPDOWN -->
               <!--<li class="dropdown" id="header_notification_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-warning-sign"></i>
                  <span class="badge">6</span>
                  </a>
               </li>-->
               <!-- END NOTIFICATION DROPDOWN -->
               <!-- BEGIN INBOX DROPDOWN -->
               <!--<li class="dropdown" id="header_inbox_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-envelope-alt"></i>
                  <span class="badge">5</span>
                  </a>
               </li>-->
               <!-- END INBOX DROPDOWN -->
               <!-- BEGIN TODO DROPDOWN -->
               <!--<li class="dropdown" id="header_task_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-tasks"></i>
                  <span class="badge">5</span>
                  </a>
               </li>-->
               <!-- END TODO DROPDOWN -->
               <!-- BEGIN USER LOGIN DROPDOWN -->
               <li class="dropdown user">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img style="width:29px;height:29px;" src="/templates/css/images/bussinessman.ico" />
                  <span class="username"><?php echo (isset($user['FullName']) && $user['FullName']) !='' ? $user['FullName'] :'Administrator'?></span>
                  <i class="icon-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu">
                     <!--<li><a href="/backend/account/profile"><i class="icon-user"></i> Tài khoản</a></li>-->
                     <li><a href="/backend/home/logout"><i class="icon-key"></i> Log Out</a></li>
                  </ul>
               </li>
               <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
         </div>
      </div>
      <!-- END TOP NAVIGATION BAR -->
   </div>
   <!-- END HEADER -->
   <!-- BEGIN CONTAINER -->
   <div class="page-container row-fluid">
      <!-- BEGIN SIDEBAR -->
      <div class="page-sidebar nav-collapse collapse">
         <!-- BEGIN SIDEBAR MENU -->
         <ul id="dashboard-menu">
            <li>
               <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
               <div class="sidebar-toggler hidden-phone"></div>
               <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <li>
				<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
				<form></form>
				<!-- END RESPONSIVE QUICK SEARCH FORM -->
			</li>
            <li class="has-sub">
               <a href="javascript:;">
                  <i class="icon-home"></i>
                  <span class="title">DASDBOARD</span>
                  <span class="arrow"></span>
               </a>
               <ul class="sub">
                  <li><a href="/backend/management/index" title="dashboard"><i class="icon-list-alt"></i> ANALYZE</a></li>
                  <li><a href="/backend/management/customer" title="Customer setting"><i class="icon-user"></i>CUSTOMER</a></li>
               </ul>
            </li>
			<li class="has-sub ">
				<a href="javascript:;">
				<i class="icon-bookmark-empty"></i>
				<span class="title">TRANSACTION</span>
				<span class="arrow"></span>
				</a>
				<ul class="sub">
					<li><a href="/backend/transaction/waiting" title="Đợi confirm"><i class="icon-repeat"></i> WAITING</a></li>
					<li><a href="/backend/transaction/confirmed" title="Đã confirm, đợi gửi tiền"><i class="icon-question-sign"></i> PAYMENT</a></li>
                    <li><a href="/backend/transaction/ph" title="Đã gửi tiền, hoàn thành giao dịch"><i class="icon-thumbs-up"></i> PAYMENT HISTORY</a></li>
                   <li><a href="/backend/transaction/policy" title="Chỉnh sửa chính sách"><i class="icon-book"></i> POLICY</a></li>
				</ul>
			</li>
            <li class="start">
               <a href="/backend/ticket">
                  <i class="icon-envelope"></i>
                  <span class="title">Ticket MANAGEMENT</span>
               </a>
            </li>
         </ul>
         <!-- END SIDEBAR MENU -->
      </div>
      <!-- END SIDEBAR -->
      <!-- BEGIN PAGE -->
      <div class="page-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->
            <div class="row-fluid">
               <div class="span12">
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <?php echo $this->layout()->content; ?>
            <!-- END PAGE CONTENT-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->
   </div>
   <!-- END CONTAINER -->
   <!-- BEGIN FOOTER -->
   <div class="footer">
      2017 &copy; Admin
      <div class="span pull-right">
         <span class="go-top"><i class="icon-angle-up"></i></span>
      </div>
   </div>
   <!-- END FOOTER -->
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37564768-1']);
    _gaq.push(['_setDomainName', 'keenthemes.com']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	//process url click
	var _sideBarCurrent = 'home';
	<?php if( isset($uri[1]) ): ?>
	_sideBarCurrent = '<?php echo $uri[1]; ?>';
	<?php endif;?>

	<?php if( isset($uri[2]) ): ?>
	<?php
		$uri2 = explode("?", $uri[2]);
	?>
	_sideBarCurrent = '<?php echo $uri2[0]; ?>';
	<?php endif;?>
	_currentAction = 'index';
	<?php if(isset($uri[3])): ?>
	<?php $uri3 = explode("?", $uri[3]); ?>
	_currentAction = '<?php echo $uri[3]; ?>';
	<?php endif;?>

	$('ul#dashboard-menu > li').each( function() {
		var liobj = $(this);
		liobj.removeClass('active');
		liobj.find('a > span.selected').remove();
		liobj.find('a > span.open').removeClass('open');
		liobj.find('ul > li').removeClass('active');

		var aObj = liobj.find('a');
		aObj.each( function() {
			hr = $(this).attr('href');
			if (hr != null && hr != 'undefined' && hr != 'javascript:;')
			{
				var res = hr.split("/");
				if(res[2]) {
					if(res[2] == _sideBarCurrent) {
						liobj.addClass('active');
						liobj.find('a:first span.selected').remove();
						liobj.find('a:first').append('<span class="selected"></span>');
						liobj.find('a > span.arrow').addClass('open');
						if(res[3]) {
							if(res[3] == _currentAction){
								$(this).parent('li').addClass('active');
							}
						}
					}
				}else if( res[1] ) {
					if( res[1] == _sideBarCurrent ) {
						liobj.addClass('active');
						liobj.find('a:first span.selected').remove();
						liobj.find('a:first').append('<span class="selected"></span>');
						liobj.find('a > span.arrow').addClass('open');
					}
				}
			}
		});
	});
  </script>
   <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
<script type="text/javascript">
	const currenturl = '<?php echo 'http://'.$_SERVER['SERVER_NAME'].':'.$_SERVER['SERVER_PORT'];?>';
 </script>
