
<!DOCTYPE html>

<html class="html" lang="en-US">

<head>

    <!-- jQuery library -->
    <script src="/templates/assets/js/jquery.2.1.3.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery.scrollbar.js"></script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

    <title>Iglama Limited - Official web page</title>
    <!-- icos -->
    <link href="/templates/images/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
    <link href="/templates/images/114.jpg" rel="apple-touch-icon" sizes="114x114"/>
    <link href="/templates/images/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
    <link href="/templates/images/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
    <link href="/templates/images/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
    <link href="/templates/images/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
    <link href="/templates/images/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
    <link href="/templates/images/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
    <link href="/templates/images/180.jpg" rel="apple-touch-icon" sizes="180x180"/>
    <link href="/templates/images/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
    <link href="/templates/images/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
    <link href="/templates/images/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
    <link href="/templates/images/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
    <link style="border-radius:4px;" href="apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
    <![endif]-->
    <!-- Other scripts -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&amp;subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/templates/css/morris.css">
    <!--[if lt IE 9]>
    <script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <style>
        .clinkedcolors{color:#2B6F98 !important;
            border-bottom:1px dashed #484848;}
    </style>

    <script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
    <script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

    <script src="/templates/js/morris.js"></script>
    <script src="/templates/js/javascript22c1.js?4241844378" type="text/javascript"></script>

    <audio id="audio-notify" controls="controls" preload="auto">
        <source src="audio/notify.html"></source>
        <source src="audio/notify-2.html"></source>
    </audio>


</head>
<body>

<div class="alertb">

    <a href="#" id="notifies" class="alert-o">
        <span class="popamount"><span class="notifycount">0</span></span>
    </a>


    <span id="notifies_block" class="intern" style = "display:none" >


<div class="tooltipy2 bottom in2 poppad">

<div class="bgpop"></div>

<div class="tooltip-inner2">


<div class="nonews">
	<div class="nonews_block">No more notifications</div>
	<img src="../ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
</div>


<div class="yesnews">

<div style="width:100%; text-align: left;margin-bottom: 5px;"><div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
</div>
<div class="fixedheight scrollbar-inner">







</div>
<a href="#" id="closeall" class="butbut">Close all</a>
</div>
</div>
</div></span>
</div>



<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
        <a id="u107" href="/" style=""></a>

        <div class="bgxs">
            <ul id="langbar">
                <li id="langbar" style="position: relative;height: 40px;" class="drop">

                    <a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>

                    <div class="dropdownContain">
                        <div class="dropOut">
                            <ul id="langbar">
                                <a href="#" class=""><li id="langbar"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/ru.png">RU</li></a>
                                <a href="#" class=""><li id="langbar"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/de.png">DE</li></a>
                                <a href="#" class=""><li id="langbar"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/pt.png">PT</li></a>
                            </ul>
                        </div>
                    </div>

                </li>
            </ul>
        </div>

        <nav class="indiv menuu119"><!-- horizontal box -->
            <ul class="hr">
                <li><a class="selected" href="/">Home</a></li>
                <li><a  href="aboutus">About us</a></li>
                <li><a  href="features">Features</a></li>
                <li><a  href="faq">FAQ</a></li>
                <li><a  href="support">Feedback</a></li>
            </ul>

        </nav>


    </div></div>

<div class="shadow Featured-In clearfix" id="page"><!-- column -->


    <div class="browser_width colelem" id="u93-bw">
        <div id="u93"><!-- group -->
            <div class="clearfix" id="u93_align_to_page">


            </div>
        </div>
    </div>


    <div class="clearfix colelem" id="pu106-6"><!-- group -->
        <div style="text-align:center;" class="Heading-H1 clearfix mse_pre_init u106-6"><!-- content -->
            <h2 class="animated fadeInLeft" style="margin-bottom:15px;">
                <span style="padding: 0 20px;"><b>Iglama Limited</b> LIMITED</span>
            </h2>
            <h4 class="animated fadeInRight">
                <span>Already <b id="land-people" data-count="515"></b> people enjoy our program</span>
            </h4>
            <a class="buttns butgreen toped" href="/customer/register"><img class="ques22" src="/templates/images/st.png">OPEN AN ACCOUNT</a>
            <a style="margin:0 0 0 15px;" class="buttns butblue toped" href="customer/login"><img class="ques22" src="/templates/images/signin.png">ENTER ACCOUNT</a>

            <h2 style="font-weight: 300;margin-top: 45px;font-size: 20px !important;color: #FFFFFF; padding: 5px 0px 5px 0px;	margin-top: 31px;">Partners already earned</h2>
            <h2 class="animated fadeInLeft" style="margin-bottom:15px;">
                <span style="background: rgba(255, 255, 255, 0.15);padding: 0 20px;"><b><span class="credited">2824061</span> $</b></span>
            </h2>
        </div>



        <div style="text-align:center;" class=" clearfix mse_pre_init stplan">
            <div class="row" style="width:100%; margin:0 auto; margin-left: -9px;">

                <!-- plan start -->


                <div class="col-md-4 exc1" style="float: left;">
                    <div class="plan text-center pl1">
                        <span class="plan-name3 "><b>PLAN</b> A</span>
                        <p class="plan-price3"><strong>4% DAILY</strong><small>FOR 30 DAYS<b></b></small></p>

                    </div>
                    <div class="arrowset mrkf fixne" style="top: -10px;"></div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="padding: 21px 0;">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>

                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable! </li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-4 exc2" style="float: left;">
                    <div class="plan text-center pl2">
                        <span class="plan-name3 "><b>PLAN</b> B</span>
                        <p class="plan-price3"><strong>4.3% DAILY</strong><small>FOR 30 DAYS<b></b></small></p>

                    </div>
                    <div class="arrowset mrkf fixne" style="top: -10px;"></div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="padding: 21px 0;">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable!</li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-4 exc3" style="float: left;">
                    <div class="plan text-center pl3">
                        <span class="plan-name3"><b>PLAN</b> C</span>
                        <p class="plan-price3"><strong>4.67% DAILY</strong><small>FOR 30 DAYS</small></p>

                    </div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="
    padding: 21px 0;
">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>

                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable!</li>

                        </ul>
                    </div>
                </div>

            </div>


        </div>


        <div class="row" style="margin-top: 120px;">
            <div class="col-md-55">
                <h3>Shortly about us</h3>
                <div class="texts just" style="padding-bottom: 20px;">Iglama Limited company is unique, promising mechanism, with affordable and cost-effective marketing approach. Which is able to provide long-term earnings prospects, people who are discovering new opportunities, seeking to gain financial well-being. <p style="padding-top: 8px;">We offer a hourly term interest rate from 4.3%. Main investment deposits can work from one to an unlimited number of days.</p></div>
                <a href="aboutus" class="buttn butblue toped" style="margin-right: 40px;"><img class="ques22" src="/templates/images/info.png">Read more about us</a>
            </div>

            <div class="col-md-512 right">
                <div class="video"></a></div>

                <h3 style="text-align: center; margin-bottom: 5px;"><!--Watch the video-->Become To Partner</h3>
                <div style="font-weight: 300;font-size: 17px;color: #26748D;text-align: center;margin-top: 4px;">
                    <!--Features of Iglama Limited Limited-->Make profits without an investment</div>
            </div>


        </div>


    </div>

    <div class="browser_width colelem" id="u320-bw" style="height: 164px;">

        <div class="bgxy"><!-- column -->
            <div class="clearfix" id="u320_align_to_page" style="padding-top: 42px;">
                <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                    <h2 style="margin-bottom:15px;font-size: 33px !important;">
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Discover new advantages and start to earn now</span>
                    </h2>
                    <a class="buttns butblue toped" href="/customer/register"><img class="ques22" src="/templates/images/account.png">Personal account</a>
                </div>









            </div>


        </div>


    </div>

    <div class="browser_width colelem" id="u320-bw">

        <div id="u320"><!-- column -->
            <div class="clearfix" id="u320_align_to_page">
                <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                    <h2 style="margin-bottom:15px;">
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;"><b>Iglama Limited</b> STATISTICS</span>
                    </h2>
                </div>
                <div style="margin-bottom: 25px;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                    <h4>
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Detailed statistics</span>
                    </h4>
                </div>

                <div style="margin:20px 0;width:100%;float:left;">
                    <div style="margin: 0px auto;position: relative;left: 31px;" class="col-md-111"><img style="position: relative;top: 3px;left: -9px;float: left;" src="/templates/images/users.png">Members<br/>
                        <b><span id="stat_count">798930</span></b></div>
                    <div class="col-md-111" style="left: 70px;"><img style="position: relative;top: 3px;left: -9px;float: left;" src="/templates/images/income.png">Total withdraw<br/><b><span id="stat_average">2824061</span>$</b></div>
                    <div class="col-md-111" style="left: 126px;"><img style="position: relative;top: 7px;left: -9px;float: left;" src="/templates/images/earn.png">Total deposited
                        <br>
                        <b><span class="credited">14217726.47</span> $</b>
                    </div>
                </div>
            </div>


            <div id="u320_align_to_page" style="padding: 0;text-align: left;">

                <a data-id="1" id="linkstat1" class="linkstat left activeon lfft" ><span class="clc11"></span><span class="clc1a">General statistics</span></a>
                <!---- 	<a data-id="2" id="linkstat2" class="linkstat left hovered" ><span class="clc1"></span><span class="clc1a">Top Investors</span></a> ----->
                <!-------	<a data-id="3" id="linkstat3" class="linkstat left hovered" ><span class="clc2"></span><span class="clc1a">Accrual history</span></a>
        -------->
            </div>

        </div>
    </div>
</div>


<div style="height: 400px;" class="browser_width colelem" id="u320-bw">

    <div class="rewback"><!-- column -->
        <div style="padding: 0;margin-top: 15px;  z-index: 0;" class="clearfix" id="u320_align_to_page">
            <div style="bottom: 0px;position:relative;" class="Heading-H2-Black clearfix colelem" id="u236-4"><!-- content -->
                <h2 style="font-size:37px !important;">Few steps to start earn now</h2>
                <div class="Subheading-Black clearfix colelem" id="u238-4"><!-- content -->
                    <p>Financial well-being is closer than you think</p>
                    <hr style="margin-top: 10px;">
                </div>
            </div>



            <div class="rower">
                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/1.png" alt=""></div>
                    <h3 style="text-align: center;margin-top: 20px;font-weight: 200;">CREATE ACCOUNT</h3>

                </div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/2.png" alt=""></div>

                    <h3 class="hdnc">OPEN NEW DEPOSIT</h3>
                </div>
                <div class="arrowset fqa"></div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/3.png" alt=""></div>

                    <h3 class="hdnc">START EARN PROFIT</h3>
                </div>
                <div class="arrowset sqa"></div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/4.png" alt=""></div>

                    <h3 class="hdnc">WITHDRAW ANYTIME</h3>
                </div>
                <div class="arrowset tqa"></div>
            </div>
        </div>
    </div>
</div>


<div class="browser_width colelem" id="u320-bw">

    <div style="height: 478px;" id="u320"><!-- column -->
        <div class="clearfix" id="u320_align_to_page">
            <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                <h2 style="margin-bottom:15px;">
                    <span class="ivi">OUR FEATURES AND MORE</span>
                </h2>
            </div>
            <div style="margin-bottom: 35px;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <h4>
                    <span>Features that makes us unique than others</span>
                </h4>
            </div>


            <div id="ourslider">
                <div id="ourslider-inner">

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/instant.png" alt=""></div>
                        <p class="center corpq2">Quickly and instantly</p>
                        <p class="just corpq">All actions occur on the page immediately - payment process, withdrawal request, and more.</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/support.png" alt=""></div>
                        <p class="center corpq2">Qualified support</p>
                        <p class="just corpq">Our experts will help you with any problem arose regarding the operation of the user software.</p>
                    </div>


                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/ui.png" alt=""></div>
                        <p class="center corpq2">Unique platform</p>
                        <p class="just corpq">Our team has developed a unique platform for user-friendly and safe to work with investments.</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/dsc.png" alt=""></div>
                        <p class="center corpq2">Earn much more</p>
                        <p class="just corpq">Complex of bonus programs, 3 levels balance boosters and three stage of unique multipliers allow to earn much more!</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/bstw.png" alt=""></div>
                        <p class="center corpq2">Perfect partnership</p>
                        <p class="just corpq">Our team guarantee to you a long-term, forward-looking, stable kind of earnings to date!</p>
                    </div>

                </div>
            </div>

        </div>

        <div class="rewback" style="margin-top: 46px;"><!-- column -->
            <div style="padding: 20px;" class="clearfix" id="u320_align_to_page">

                <div style="float:left;">
                    <h3 >Open an account now</h3>
                    <p style="font-size: 16px;font-weight: 300;width: 580px;">To start your first financial activity, please sign up by simple registration form.</p>
                </div>
                <div style="float:right;padding: 20px 0;">
                    <a class="buttns butblue toped" href="/customer/register"><img class="ques22" src="/templates/images/account.png">Personal account</a>
                </div>

            </div>

        </div>


    </div>





</div>
</div>
<div id="video" class="modalDialog3" style="display:none;">
    <div class="video-inner" style="width: 680px;">
        <a href="#close" title="Close" class="close closeVideo"></a>
        <div class="xmodal" style="height: 58px;"><h2 style="padding-top: 18px;font-size: 35px !important;font-weight:200;">Iglama Limited Limited</div>

        <div class="bgmodal" style="padding: 0px 0px 0 0px;">


            <div style="margin-top: 20px;margin-bottom: 20px;">
                <iframe width="680" height="315" frameborder="0" allowfullscreen></iframe>

                <div style="text-align: center;padding: 15px 15px 15px 15px;clear: both;height: 43px;">
                    <div style="clear: both;"><span style="font-weight: 300;font-size: 25px;position: relative;top: 4px;float: left;">Still don't have an account?</span>  <a style="float: right;" class="buttn butcgreen" href="/customer/register">Open an account</a></div></div>
            </div>


        </div>
    </div>
</div>
<script>$('.credited').accrued({speed:0.00147177,dig:6});</script>
<!-- column -->
<div class="clearfix"></div>
<!------
<div id="infobox"><span></span></div>bi trung code tren server, rieng phan public may revert roi update ve di, phan imag, js, css tao them roi...ko hiểu

----->
<div id="alarms"></div>
<div class="osd widj">


    <div class="footer" style="padding-bottom: 25px;"><!-- column -->
        <div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

            <div style="" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <h4><span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Accepting payment systems like</span></h4>
                <div style="padding: 22px 0px 0 140px;">
<!--                    <div style="background:url('/templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>-->
                    <div style="background:url('/templates/images/bt.png') no-repeat; width: 129px; height:50px;float:left;padding-right: 70px;"></div>
<!--                    <div style="background:url('/templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>-->
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top: -37px;"><!-- column -->
        <footer>

            <div class="footero">
                <div class="contain">
                    <div class="stpnw"><img width="170" src="/templates/images/logo.png" class="instq"> © 2017
                        <div style="padding-top: 27px;">Superiority and uniqueness, is the slogan of our company.</div>
                    </div>
                    <div class="fixtd3">

                        <div style="padding: 2px 0px;"><a href="/" class="footerlink">Home</a></div>
                        <div style="padding: 2px 0px;"><a href="aboutus" class="footerlink">About us</a></div>
                        <div style="padding: 2px 0px;"><a href="support" class="footerlink">Feedback</a></div>

                    </div>



                    <div class="fixtd2">

                        <div style="padding: 2px 0px;"><a href="faq" class="footerlink">FAQ</a></div>
                        <div style="padding: 2px 0px;"><a href=terms" class="footerlink">Terms of use</a></div>

                    </div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
                        <div style="padding: 2px 0px;"><a href="features" class="footerlink">Features</a></div>
                        <div style="padding: 2px 0px;"></div>

                    </div>


                    <div class="fixtd">

                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Iglama Limited Limited</a></div>

                    </div>
                </div>
            </div>
        </footer>
    </div>


</div>


</body>
</html>