<?php
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<!DOCTYPE html>

<html class="html" lang="en-US">

<head>

    <!-- jQuery library -->
    <script src="/templates/assets/js/jquery.2.1.3.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery.scrollbar.js"></script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

    <title>WALK FUNDS - Official web page</title>
    <!-- icos -->
    <link href="/templates/images/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
    <link href="/templates/images/114.jpg" rel="apple-touch-icon" sizes="114x114"/>
    <link href="/templates/images/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
    <link href="/templates/images/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
    <link href="/templates/images/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
    <link href="/templates/images/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
    <link href="/templates/images/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
    <link href="/templates/images/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
    <link href="/templates/images/180.jpg" rel="apple-touch-icon" sizes="180x180"/>
    <link href="/templates/images/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
    <link href="/templates/images/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
    <link href="/templates/images/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
    <link href="/templates/images/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
    <link style="border-radius:4px;" href="apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
    <![endif]-->
    <!-- Other scripts -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&amp;subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/templates/css/morris.css">
    <!--[if lt IE 9]>
    <script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <style>
        .clinkedcolors{color:#2B6F98 !important;
            border-bottom:1px dashed #484848;}
    </style>

    <script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
    <script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

    <script src="/templates/js/morris.js"></script>
    <script src="/templates/js/javascript22c1.js?4241844378" type="text/javascript"></script>

    <audio id="audio-notify" controls="controls" preload="auto">
        <source src="audio/notify.html"></source>
        <source src="audio/notify-2.html"></source>
    </audio>


</head>
<body>
<script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/58b45ee778d62074c0949bb3/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
</script>
<div class="alertb">

    <a href="#" id="notifies" class="alert-o">
        <span class="popamount"><span class="notifycount">0</span></span>
    </a>


    <span id="notifies_block" class="intern" style = "display:none" >


<div class="tooltipy2 bottom in2 poppad">

<div class="bgpop"></div>

<div class="tooltip-inner2">


<div class="nonews">
	<div class="nonews_block">No more notifications</div>
	<img src="../ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
</div>


<div class="yesnews">

<div style="width:100%; text-align: left;margin-bottom: 5px;"><div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
</div>
<div class="fixedheight scrollbar-inner"></div>
<a href="#" id="closeall" class="butbut">Close all</a>
</div>
</div>
</div></span>
</div>

<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
        <a id="u107" href="/" style=""></a>

        <div class="bgxs">
            <ul id="langbar">
                <li id="langbar" style="position: relative;height: 40px;" class="drop">

                    <a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>

                </li>
            </ul>
        </div>

        <nav class="indiv menuu119"><!-- horizontal box -->
            <ul class="hr">
                <li><a class="<?php if($actionName=="index"){?>selected <?php }?>" href="/">Home</a></li>
                <li><a  class="<?php if($actionName=="aboutus"){?>selected <?php }?>" href="/aboutus">About us</a></li>
                <li><a  class="<?php if($actionName=="features"){?>selected <?php }?>" href="/features">Features</a></li>
                <li><a  class="<?php if($actionName=="faq"){?>selected <?php }?>" href="/faq">FAQ</a></li>
                <li><a  class="<?php if($actionName=="support"){?>selected <?php }?>" href="/support">Feedback</a></li>
            </ul>

        </nav>


    </div></div>

<?php echo $this->layout()->content; ?>
<div id="alarms"></div>
<div class="osd widj">

    <div class="footer" style="padding-bottom: 25px;"><!-- column -->
        <div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

            <div style="display: inline-block;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <span style="display:inline-block; font-size: x-large">Accepting payment systems with
                        <img src='../templates/images/bt.png' style="width: 75px; height:25px;">
                    </span>
                <!--                <div style="padding: 22px 0px 0 140px;">-->
                <!--                    <div style="background:url('../templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>-->
                <!--                    <div style="background:url('../templates/images/bt.png') no-repeat; width: 129px; height:50px;"></div>-->
                <!--                    <div style="background:url('../templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>-->
                <!--                </div>-->
            </div>
        </div>
    </div>
    <div style="margin-top: -37px;"><!-- column -->
        <footer>
            <div class="footero">
                <div class="contain">
                    <div class="stpnw"><img width="170" src="/templates/images/logo.png" class="instq"> © 2017
                    </div>
                    <div class="fixtd3">

                        <div style="padding: 2px 0px;"><a href="/" class="footerlink">Home</a></div>
                        <div style="padding: 2px 0px;"><a href="/aboutus" class="footerlink">About us</a></div>
                        <div style="padding: 2px 0px;"><a href="/support" class="footerlink">Feedback</a></div>

                    </div>
                    <div class="fixtd2">

                        <div style="padding: 2px 0px;"><a href="/faq" class="footerlink">FAQ</a></div>
                        <div style="padding: 2px 0px;"><a href=/features" class="footerlink">Terms of use</a></div>

                    </div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
                        <div style="padding: 2px 0px;"><a href="features" class="footerlink">Features</a></div>
                        <div style="padding: 2px 0px;"></div>

                    </div>
                    <div class="fixtd">

                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">walkfunds.com</a></div>

                    </div>
                </div>
            </div>
        </footer>
    </div>


</div>


</body>
</html>