
<div class="footer-top container">
	<div class="">
		<div class="row">
			<div class="col-lg-8 col-xs-12" style="padding: 5px 0px 0px 25px;">
				<h6 class="tittle"><?php echo $this->about['about_name'];?></h6>
				<ul class="bottom-menu">
					<li class=""><a href="#">Địa chỉ :<?php echo $this->about['about_address'];?></a></li>
					<li class=""><a href="#"><?php echo $this->about['about_mobile'];?></a></li>
					<li class=""><a href="#">Email: <?php echo $this->about['about_email'];?></a></li>
				</ul>
			</div>
			<div class="col-lg-4 col-xs-12" style="padding-top: 60px;">
				<div class="social-footer1">
					<a class="fa fa-facebook" target="_blank" href="#" title="Facebook"
						style="visibility: visible;"></a> <a class="fa fa-twitter"
						target="_blank" href="#" title="Facebook"
						style="visibility: visible;"></a> <a class="fa fa-google"
						target="_blank" href="#" title="Facebook"
						style="visibility: visible;"></a> <a class="fa fa-youtube-play"
						target="_blank" href="#" title="Facebook"
						style="visibility: visible;"></a> <a class="fa  fa-linkedin"
						target="_blank" href="#" title="Facebook"
						style="visibility: visible;"></a>
				</div>
				<span style="color: #fff;">Copyright by Pharbaco</span>
			</div>
		</div>
	</div>
</div>
<a id="yt-totop" href="#" title="Go to Top" class="fa fa-arrow-up"></a>