<?php
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<!DOCTYPE html>

<html class="html" lang="en-US">
<head>

	<!-- jQuery library -->
	<script src="/templates/js/jquery.2.1.3.min.js" type="text/javascript"></script>
	<script src="/templates/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
	<script src="/templates/js/jquery.scrollbar.js"></script>
	<script src="/templates/js/jquery-migrate-1.2.1.js"></script>
	<script src="/templates/js/jquery-ui.js"></script>
	<script src="/templates/js/jquery.alerts.js"></script>

	<meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

	<title><?php echo $this->title;?></title>
	<!-- icos -->
	<link href="/templates/images/apple/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
	<!--<link href="/templates/images/apple/114.jpg" rel="apple-touch-icon" sizes="114x114"/>-->
	<link href="/templates/images/apple/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
	<link href="/templates/images/apple/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
	<link href="/templates/images/apple/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
	<link href="/templates/images/apple/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
	<link href="/templates/images/apple/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
	<link href="/templates/images/apple/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
	<!--<link href="/templates/images/apple/180.jpg" rel="apple-touch-icon" sizes="180x180"/>-->
	<link href="/templates/images/apple/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
	<link href="/templates/images/apple/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
	<link href="/templates/images/apple/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
	<link href="/templates/images/apple/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
	<!--<link style="border-radius:4px;" href="/templates/images/apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>-->
	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
	<link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
	<link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
	<!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
	<![endif]-->
	<!-- Other scripts -->
	<link type="text/css" rel="stylesheet" href="/templates/css/jquery.alerts.css">
	<link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/templates/js/morris.css">
	<!--[if lt IE 9]>
	<script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
	<![endif]-->
	<style>
		.clinkedcolors{color:#2B6F98 !important;
			border-bottom:1px dashed #484848;}
	</style>

	<script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
	<script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

	<script src="/templates/js/morris.js"></script>
	<!--<script src="/templates/js/javascript.js?4241844378" type="text/javascript"></script>-->

	<!--<audio id="audio-notify" controls="controls" preload="auto">
		<source src="audio/notify.mp3"></source>
		<source src="audio/notify.ogg"></source>
	</audio>-->
</head>
<body>
<script type="text/javascript" crossorigin="*">

	var _globalRateType = "BTC";
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/58b45ee778d62074c0949bb3/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
	})();
	$(document).ready(function() {
		try {
			$(document).on('click', '.toggle_ref_balance', function() {
				try {
					var urlRate = "https://blockchain.info/tobtc?currency=USD&value=1";
					$.get("https://blockchain.info/tobtc?currency=USD&value=1").done(function (data) {
						console.log(data);
					});
					/*$.ajax({
						type		:	'GET',
						url			:	urlRate,
						dataType	:	'html',
						data		:	{},
						crossOrigin: "*",
						success: function(res) {
							alert(res);
						},
						error: function(res) {
							//nothing
						},
					});*/
				} catch (e) {
					alert('.toggle_ref_balance' + e.message);
				}
			});

		} catch (e) {
			alert('ready' + e.message);
		}
	});

</script>
<div class="alertb">

	<a href="#" id="notifies" class="alert-o">
		<span class="popamount"><span class="notifycount">0</span></span>
	</a>

  
  <span id="notifies_block" class="intern" style = "display:none" >
  
  
<div class="tooltipy2 bottom in2 poppad">

	<div class="bgpop"></div>

	<div class="tooltip-inner2">


		<div class="nonews">
			<div class="nonews_block">No more notifications</div>
			<img src="https://ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
		</div>


		<div class="yesnews">

			<div style="width:100%; text-align: left;margin-bottom: 5px;">
				<div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
			</div>
			<div class="fixedheight scrollbar-inner">
			</div>
			<a href="#" id="closeall" class="butbut">Close all</a>
		</div>
	</div>
</div></span>
</div>

<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
		<a id="u107" href="/" style=""></a>

		<div class="bgxs">
			<ul id="langbar">
				<li id="langbar" style="position: relative;height: 40px;" class="drop">

					<a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>
				</li>
			</ul>
		</div>

		<nav class="indiv menuu119"><!-- horizontal box -->
			<ul class="hr">
				<li><a href="/">Home</a></li>

				<li><a href="/aboutus">About us</a></li>
				<li><a href="/terms">Features</a></li>
				<li><a href="/faq">FAQ</a></li>
				<li><a href="/support">Feedback</a></li>
			</ul>

		</nav>


	</div></div><div class="shadow Featured-In clearfix" id="page" style="width: 1200px;">
	<!-- column -->

	<style>
		.inheader{
			padding:10px 10px;
			background:#065871; border:1px solid #065871; color:#fff;
			font-size:11px; font-weight:bold;}
		table.accmain td,
		.item,
		.item2,
		.item3{
			padding:2px 10px;
			background:#fff; border:1px solid #065871; color:#065871;}

		.mons td{	background:#fff; border:1px solid #065871; padding:10px 0px; text-align:center; color:#0b191b;}
	</style>



	<div class="browser_width colelem" id="u93-bw">
		<div class="u92xx">

		</div>
	</div>


	<div style="margin-top: -257px;" class="clearfix colelem" id="pu106-6"><!-- group -->

		<div class="topboxes"><!-- content -->

			<div class="animated fadeInUp" style="float:left; margin-left: 114px;">
				<div class="boxed">
					<span class="hbox">TOTAL BALANCE</span>
					<span class="countbox"><span class="usd_balance"><?php echo isset($this->dataReportMember['amountInvest'])?$this->dataReportMember['amountInvest']:0;?><span> <span class="dv">BTC</span></span><span class="ibox1">Deposited: <b><?php echo isset($this->dataReportMember['amountInvest'])?$this->dataReportMember['amountInvest']:0;?> <span class="dv">BTC</span></b></span><span class="ibox2">Withdrawn: <b><?php echo isset($this->dataReportMember['amountSuccessRecived'])?$this->dataReportMember['amountSuccessRecived']:0;?> <span class="dv">BTC</span></b></span></span></span>
				</div>
			</div>

			<div class="animated fadeInUp" style="float:left;margin-left:30px;">
				<div class="boxed">
					<span class="hbox">EARNED TOTAL</span>
					<span class="countbox"><span class="usd_balance"><?php echo isset($this->dataReportMember['amountSuccessRecived'])?$this->dataReportMember['amountSuccessRecived']:0;?><span> <span class="dv">BTC</span></span></span>
					<span class="ibox1">Last Deposited: <b> <span class="usd_balance"><?php echo isset($this->dataReportMember['amountConfirmedInvestLast'])?$this->dataReportMember['amountConfirmedInvestLast']:0;?></span><span class="dv">BTC</span></b></span>
					<span class="ibox2">Last Withdrawn: <b> <span class="usd_balance"><?php echo isset($this->dataReportMember['amountSuccessRecivedLast'])?$this->dataReportMember['amountSuccessRecivedLast']:0;?></span><span class="dv">BTC</span></b></span>
				</div>

				<div>
					<div class="booster1">
						<div class="txtsz">
							<div id="somex">GET BOOSTER BY RAISING BALANCES<a href="#"><img width="13"src="/templates/images/help.png"class="helpdesk"></a>
								<span id="somee">
<div class="tooltipy bottom in" style="margin-top: 0px; margin-left: 5px;">

	<div class=""
		 style="border-color: transparent;  border-style: solid;  height: 0;  position: relative;  width: 0; border-bottom-color: #fa582d;   border-width: 0px 25px 20px 25px;left: 114px;margin-top: -4px;top: 4px;"></div>

</div></span>
							</div>
						</div>
					</div>

				</div>
			</div>
			<div class="animated fadeInUp" style="float:left;margin-left:30px;">


				<div class="front refblock">
					<div class="boxed">
						<span class="hbox">ACTIVE DEPOSIT</span>
						<span class="countbox"><span class="usd_balance"><?php echo isset($this->dataReportMember['amountSuccessRecivedLast'])?$this->dataReportMember['amountSuccessRecivedLast']:0;?></span><span class="dv">BTC</span></span>
						<span class="ibox1">EARNED: <b><span class="usd_balance"><?php echo isset($this->dataReportMember['amountConfirmedInvestLast'])?$this->dataReportMember['amountConfirmedInvestLast']:0;?></span><span class="dv">BTC</span></b></span>
						<span class="ibox2">Withdrawn: <b><span class="usd_balance"><?php echo isset($this->dataReportMember['planRecivedLast'])?$this->dataReportMember['planRecivedLast']:0;?></span><span class="dv">BTC</span></b></span>

					</div>
					<div class="btstat toggle_ref_balance"></div>
				</div>


				<div class="back refblock">
					<div class="boxed">
						<span class="hbox">REFERRAL BALANCE</span>
						<span class="countbox"><span id="btc_ref_balance">$</span> $</span>
						<span class="ibox1">EARNED: <b>$$</b></span>
						<span class="ibox2">Withdrawn: <b>0.00 $</b></span>
					</div>
					<div class="usdstat toggle_ref_balance"></div>
				</div>


			</div>
		</div>
	</div>
	<div class="shadow Featured-In clearfix" id="page" style="width: 1200px;">
		<div class="clearfix"></div>
	</div>
	<div class="browser_width colelem" style="">

		<div class="boxybot">
			<div class="clearfix" id="u320_align_to_page" style="padding: 10px 0;">

				<div style="" class="Subheading-White clearfix colelem" id="u825-4">

					<div class="boxed1"><img class="ques" src="/templates/images/reps.png"><b>pentest</b></div>

					<div class="boxed2"><img class="ques" src="/templates/images/earnings.png">Instant Payment: <b>Active</b></div>

					<div class="boxed3"><img class="ques" src="/templates/images/chartcab.png">Status <b>ON</b></div>
				</div>
			</div>
		</div>
	</div>

	<div style="height: 100%; width: 1200px;" class=" clearfix colelem taining">
		<div style="float:left;width: 30%;font-size: 19px;padding-bottom: 100px;">
			<div class="cabinem"><div class="cabinem2">
					<ul id="cab_nav">
						<li class="<?php if($actionName =='main'){ ?>active<?php }?>"><a href="/frontend/member/main"><img class="mrgn" src="/templates/images/main.png"><span class="nav">Main page</span></a></li>
						<li class="<?php if($actionName =='invest'){ ?>active<?php }?>"><a href="/frontend/member/invest"><img class="mrgn" src="/templates/images/newdep.png"><span class="nav">New deposit</span></a></li>
						<li class="<?php if($actionName =='history'){ ?>active<?php }?>"><a href="/frontend/member/history"><img class="mrgn" src="/templates/images/cashout.png"><span class="nav">Make withdrawal</span></a></li>
						<!--<li ><a href="?a=referals"><img class="mrgn" src="/templates/images/refs.png"><span class="nav">Referral section</span></a></li>-->
						<li class="<?php if($actionName =='ticketlist'){ ?>active<?php }?>"><a href="/frontend/member/ticketlist"><img class="mrgn" src="/templates/images/imgadvert.png"><span class="nav">Ticket</span></a></li>
						<li class="<?php if($actionName =='investstatus'){ ?>active<?php }?>"><a href="/frontend/member/investstatus"><img class="mrgn" src="/templates/images/logs.png"><span class="nav">Action logs</span></a></li>
						<li class="<?php if($actionName =='index'){ ?>active<?php }?>"><a href="/frontend/member"><img class="mrgn" src="/templates/images/settings.png"><span class="nav">My profile</span></a></li>
						<li class="<?php if($actionName =='logout'){ ?>active<?php }?>"><a href="/frontend/register/logout"><img class="mrgn" src="/templates/images/signout.png"><span class="nav">Sign out</span></a>

						</li>
					</ul>
				</div>
			</div>
			<div class="transactions" style="margin-top: 5px;"><div class="cabinem2">
					<h4 style="color: #fff;    text-align: center;    padding: 14px 0px 0px 0;">New transactions</h4>
					<?php if (!isset($this->dataReportMember['transactionGHLastID']) || 1*$this->dataReportMember['transactionGHLastID']==0){?>
					<div style="padding: 10px 0 0 0;">
						<div style="background: rgba(255, 255, 255, 0.2);">
							<div style="padding: 8px 15px;">
								<div style="color:#fff;font-size: 15px;font-weight: 300;font-weight: 700;">NA</div>
								<div style="float: left;margin-top: 5px;padding-right: 10px;"><img width="16px;" src="/templates/images/depcabin.png"/></div>
								<div style="color: #FFF;  font-size: 15px;  font-weight: 300;margin-top: 7px;">No Investor Found <b style="font-size: 18px;margin-top: -13px; margin-left: -11px;text-align: right;float: right;">NA</b>
								</div>
							</div>
						</div>
					</div>
					<?php }else{?>
					<div style="color:#fff;font-size: 15px;font-weight: 300;font-weight: 700;    padding: 25px 25px 0px 70px;">
						<span>- EARNED: <b><span class="btc_balance"><?php echo isset($this->dataReportMember['amountConfirmedInvestLast'])?$this->dataReportMember['amountConfirmedInvestLast']:0;?></span><span class="dv">BTC</span></b></span>
					</div>
					<div style="color:#fff;font-size: 15px;font-weight: 300;font-weight: 700;     padding: 25px 25px 0px 70px;">
							<span>- Total Withdrawn: <b><span class="btc_balance"><?php echo isset($this->dataReportMember['planRecivedLast'])?$this->dataReportMember['planRecivedLast']:0;?></span><span class="dv">BTC</span></b></span>
					</div>

					<?php }?>
					<div style="text-align: center;width: 100%;padding:15px 0;clear: both;"><a class="office_load buttn butcgreen" href="/frontend/member/invest">New deposit</a></div>
				</div></div>
		</div>
		<div class="rght padbot">
			<!-- <div id="cab_loading"></div>-->
			<div id="cab_content" style="position: relative;">
				<!--ajax-->
				<div style="padding-bottom:24px;" class="bgcab">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
			<!--/ajax-->
		</div>
	</div>
</div>
</div><!-- column -->
<div class="clearfix"></div>

<div class="ftbg1">
	<div class="fixbg1">
		<div class="clr"></div>
	</div>
</div>


</div><!-- column -->
<div class="clearfix"></div>
<div class="osd widj">


	<div class="footer" style="padding-bottom: 25px;"><!-- column -->
		<div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

			<div style="" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
				<h4><span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Accepting payment systems like</span></h4>
				<div style="padding: 22px 0px 0 140px;">
					<div style="background:url('/templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>
					<div style="background:url('/templates/images/bt.png') no-repeat; width: 129px; height:50px;float:left;padding-right: 70px;"></div>
					<div style="background:url('/templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>
				</div>
			</div>
		</div>
	</div>
	<div style="margin-top: -37px;"><!-- column -->
		<footer>

			<div class="footero">
				<div class="contain">
					<div class="stpnw"><img width="170" src="/templates/images/logo.png" class="instq"> © 2017
						<div style="padding-top: 27px;">Superiority and uniqueness, is the slogan of our company.</div>
					</div>
					<div class="fixtd3">

						<div style="padding: 2px 0px;"><a href="?a=home" class="footerlink">Home</a></div>
						<div style="padding: 2px 0px;"><a href="?a=cust&page=about" class="footerlink">About us</a></div>
						<div style="padding: 2px 0px;"><a href="?a=support" class="footerlink">Feedback</a></div>

					</div>



					<div class="fixtd2">

						<div style="padding: 2px 0px;"><a href="?a=faq" class="footerlink">FAQ</a></div>
						<div style="padding: 2px 0px;"><a href="?a=rules" class="footerlink">Terms of use</a></div>

					</div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
						<div style="padding: 2px 0px;"><a href="?a=cust&page=features" class="footerlink">Features</a></div>
						<div style="padding: 2px 0px;"></div>

					</div>


					<div class="fixtd">

						<div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
						<div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
						<div style="padding: 2px 0px;"><a href="#" class="footerlink">Iglama Limited Limited</a></div>

					</div>
				</div>
			</div>
		</footer>
	</div>


</div>


</body>
</html>