<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title><?php echo $this->title;?></title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link rel="shortcut icon" href="/templates/images/green_dollar.ico" type="image/x-icon">
	<meta content="" name="description" />
	<meta content="" name="author" />
	<link href="/templates/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/templates/assets/css/metro.css" rel="stylesheet" />
	<link href="/templates/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
	<link href="/templates/assets/css/style.css" rel="stylesheet" />
	<link href="/templates/assets/css/style_responsive.css" rel="stylesheet" />
	<link href="/templates/assets/css/style_default.css" rel="stylesheet" id="style_color" />
	<link rel="stylesheet" type="text/css" href="/templates/assets/uniform/css/uniform.default.css" />
	<link rel="stylesheet" type="text/css" href="/templates/css/bootbox.css" />
	<link rel="shortcut icon" href="/templates/css/images/favicon.ico" />
	<script src="/templates/assets/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src = "/templates/js/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src = "/templates/js/jquery-migrate-1.2.1.js"></script>
	<script type="text/javascript">
		var jQuery_1_11_0 = $.noConflict(true);
	</script>
	<script type="text/javascript" src ="/templates/js/bootbox.min.js"></script>
	<script src="/templates/assets/bootstrap/js/bootstrap.min.js"></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN LOGO -->
<div class="logo">
	<!-- <img src="/templates/assets/img/logo-big.png" alt="" /> -->
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<?php echo $this->layout()->content; ?>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
	2015 &copy; Admin Dashboard.
</div>
  <!-- END COPYRIGHT -->
  <!-- BEGIN JAVASCRIPTS -->
  <script src="/templates/assets/js/jquery-1.8.3.min.js"></script>
  <script src="/templates/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/templates/assets/uniform/jquery.uniform.min.js"></script>
  <script src="/templates/assets/js/jquery.blockui.js"></script>
  <script src="/templates/assets/js/app.js"></script>
  <script>
    jQuery(document).ready(function() {
      App.initLogin();
    });
  </script>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37564768-1']);
    _gaq.push(['_setDomainName', 'keenthemes.com']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>